import HeaderServer from "@/components/globals/header/HeaderServer";
import "../styles/globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={``}>
        <HeaderServer />
        {children}
      </body>
    </html>
  );
}
